version: '3.8'
services:
  db-mysql:
    image: mysql:latest
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: examen
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:

    